services:
  auth-srv:
    build:
      context: .
      dockerfile: ./apps/auth-srv/Dockerfile
      target: development
    command: yarn start:dev auth-srv
    env_file:
      - ./apps/auth-srv/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: